# Generated by Django 6.0.3 on 2026-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available 🟢'), ('picked_up', 'Picked Up 🚗'), ('completed', 'Completed ✅')], default='available', max_length=20),
        ),
    ]
