# Generated by Django 6.0.3 on 2026-03-27 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddonation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='unit',
            field=models.CharField(choices=[('plates', 'Plates'), ('kg', 'Kilograms'), ('boxes', 'Boxes'), ('packets', 'Packets')], default='plates', max_length=20),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='hours_until_expiry',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='available', max_length=20),
        ),
    ]
